---
- name: update apt cache
  apt: update_cache=yes cache_valid_time=86400

- name: update all installed packages
  apt: only_upgrade=yes

- name: install WireGuard packages
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - 'wireguard'
