---
- name: install ELRepo and EPEL repositories
  yum:
    name: '{{ item }}'
    state: present
    update_cache: yes
  loop:
  - 'elrepo-release'
  - 'epel-release'

- name: install WireGuard packages
  yum:
    name: '{{ item }}'
    state: present
  loop:
  - 'kmod-wireguard'
  - 'wireguard-tools'
