---
name: release

on:
  push:
    tags:
    - '*'

defaults:
  run:
    working-directory: raylas.wireguard

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        path: raylas.wireguard
  
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Ansible
      run: pip3 install ansible-base

    - name: Import role to Ansible Galaxy
      run: ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }} $(echo ${{ github.repository }} | cut -d/ -f1) $(echo ${{ github.repository }} | cut -d/ -f2)
